name: scale3c
description: S3C demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  navigation:
    path: navigation
  core:
    path: core
  core_ui:
    path: core_ui
  data:
    path: data
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - core/resources/langs/
    - core_ui/resources/icons/
    - core_ui/resources/images/
