name: core_ui
description: Core UI package
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^2.0.6
  responsive_builder: ^0.7.0
  flutter_bloc: ^8.1.3
  google_fonts: 4.0.2
  cached_network_image: 3.2.3
  pull_to_refresh: 2.0.0

  core:
    path: ../core
  navigation:
    path: ../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
